version: '3.8'

services:
  statistics-app:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./statistics:/srv/shiny-server/statistics
      - ./data:/srv/shiny-server/data
    environment:
      - R_MAX_MEM_SIZE=2G
    restart: unless-stopped
    container_name: ali-yalcinkaya-statistics

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - statistics-app
    restart: unless-stopped
    container_name: ali-yalcinkaya-nginx
