version: '3.8'

services:
  statistics-app:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./statistics:/srv/shiny-server/statistics
      - ./data:/srv/shiny-server/data
    environment:
      - R_MAX_MEM_SIZE=2G
      - SHINY_LOG_LEVEL=INFO
    restart: unless-stopped
    container_name: ali-yalcinkaya-statistics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3838/statistics/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - statistics-app
    restart: unless-stopped
    container_name: ali-yalcinkaya-nginx

  # Monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    container_name: ali-yalcinkaya-prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    container_name: ali-yalcinkaya-grafana

volumes:
  grafana-storage:
