name: Update Google Scholar Publications

on:
  schedule:
    - cron: "0 0 * * 0" # Her pazar gece 12'de çalışır
  workflow_dispatch:

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install scholarly serpapi

      - name: Fetch Google Scholar publications
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python scripts/fetch_scholar.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add _data/publications.json
          git commit -m "Update Google Scholar publications" || echo "No changes to commit"
          git push
